OOP school library: add basic UI
AmaliaGM/OOPSlibrary pull request #4
Opened 2022-10-28 19:18 UTC by AmaliaGM

## Project requirements

- Watch the video with the UI example again (you have seen it while reading the Sneak Peek).
UI example
- Your console app should behave in the same way as it is in the example.
- Create a app.rb file that will serve as your console app entry-point. It should have methods that do the following:
List all books.
List all people.
Create a person (teacher or student, not a plain Person).
Create a book.
Create a rental.
List all rentals for a given person id.
- In your main.rb define the entry point, this will be a method called main that is invoked at the end of your file. This method should do the following:
Present the user with a list of options to perform.
Lets users choose an option.
If needed, ask for parameters for the option.
Have a way to quit the app.

2022-10-28 19:49 UTC, Rustamxon7 requested changes
Hello @AmaliaGM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
_Your project is almost complete!_
_No Linters errors_

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 19:49 UTC, Rustamxon7 commented on main.rb
> +require_relative './app'
- [ ] You did great job. However, If I run the app I'm getting several errors. Kindly fix them to make your project approve. In order to check your project, your app need to be fully functional and not showing errors. You can see errors in this video:

https://user-images.githubusercontent.com/69011963/198720498-e78895e9-bf7f-4fe6-8aa5-76f46b231a32.mov

2022-10-28 22:12 UTC, codepantha requested changes
# STATUS: REQUIRES CHANGES ♻️ 

## Hi @AmaliaGM 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights 🎯 
✔️ Descriptive PR
✔️ Used GitFlow correctly
✔️ No linter errors

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] An error that didn't exist previously now occurs in the `student.rb` file when I try to start the app. Please see the image below and try to fix it 👇 
![image](https://user-images.githubusercontent.com/46839548/198740602-02dd5de6-bc4a-4464-860f-59945c2afadd.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 23:06 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @AmaliaGM,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ You used Gitflow correctly 👍 
✅ Linter checks passed 👍

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-10-28 23:06 UTC, AmaduKamara commented on person.rb
> +    case option
You're doing great so far, but just as the previous reviewer highlighted, the creation of a person is still giving errors and crashes the program. 

- [ ] When I'm creating a person, a student, or a teacher, the error comes from this section of your code. Kindly check this method and fix the error given when selecting either Y/N for parent permission for every creation of a person.

**See the screenshot below**
![image](https://user-images.githubusercontent.com/50941074/198748480-f24e57af-315c-4410-b543-b6ca2c2fabda.png)

2022-10-29 01:29 UTC, Ismailco requested changes
### Hi @AmaliaGM, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 01:29 UTC, Ismailco commented on app.rb
> +    when '2' then list_all_persons
- [ ] As the previous reviewers mentioned your app produces some errors, kindly fix them so your app is working properly
- When listing the people the app crashes and produces this error:
![Screenshot_20221029_022441](https://user-images.githubusercontent.com/25227022/198755627-bf8d6c96-1f67-468f-94f6-73a82a5c635d.png)

- When trying to create a rental the app crashes and produces this error:
![Screenshot_20221029_022528](https://user-images.githubusercontent.com/25227022/198755652-37f4e19e-8482-41b2-ab71-22111da8e388.png)

2022-10-29 19:27 UTC, vickymarz requested changes
Hi @AmaliaGM, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 19:27 UTC, vickymarz commented on person.rb
> +    age = Interger(gets.chomp)
- [ ] I got this error while trying to create a student. It seems you misspelled Integer 👇🏽 

![image](https://user-images.githubusercontent.com/63473584/198849042-1648f9dc-3d8d-4e18-8f48-578c8c830b4a.png)

2022-10-29 19:27 UTC, vickymarz commented on person.rb
> +    person = Student.new(classroom, age, name, parent_permission)
- [ ] After correcting the name error locally, i still cant create/add a STUDENT. I was getting this error. Kindly look into it 

![image](https://user-images.githubusercontent.com/63473584/198849264-83e86570-e6ef-44cc-9fa2-1f385c6f922a.png)

2022-10-29 22:00 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @AmaliaGM,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-07 17:41 UTC, merged